function f=steadystate_union(x0,param)

kappa=param(1);
v=param(2);
sigma=param(3);
nl=param(4);
nh=param(5);
zeta=param(6);
theta=param(7);
KAd=param(8);
KLAmax=param(9);
KHAmax=param(10);
lambda=param(11);
phi=param(12); 
kappaB=param(13);
vB=param(14);
sigmaB=param(15);
nlb=param(16);
nhb=param(17);
thetaB=param(18);
KBd=param(19);
KLBmax=param(20);
KHBmax=param(21);
lambB=param(22);
phiB=param(23); 

%Initial conditions:

cla=x0(1);
cha=x0(2);
hla=x0(3);
hha=x0(4);
wa=x0(5);
ra=x0(6);
kla=x0(7);
kha=x0(8);
clb=x0(9);
chb=x0(10);
hlb=x0(11);
hhb=x0(12);
wb=x0(13);
rb=x0(14);
klb=x0(15);
khb=x0(16);
%We write the equilibrium conditions:
f(1)=(1-phi)*cla^(-sigma)*lambda*(wa*hla*nl)^(-phi)*wa*nl-kappa*hla^(1/v)
f(2)=(1-phi)*cha^(-sigma)*lambda*(wa*hha*nh)^(-phi)*wa*nh-kappa*hha^(1/v)
f(3)=nl*ra*kla^(nl-1)-rb
f(4)=nh*ra*kha^(nh-1)-rb
f(5)=(1-theta)*zeta*(kla+kha-KBd*klb+khb)^(-theta)*(nl*hla+nh*hha)^(theta)-ra; 
f(6)=theta*zeta*(kla+kha-KBd*klb+khb)^(1-theta)*(nl*hla+nh*hha)^(theta-1)-wa;
f(7)=lambda*(wa*hla*nl)^(1-phi)+ra*kla^nl+rb*(KLAmax-kla)-cla
f(8)=lambda*(wa*hha*nh)^(1-phi)+ra*kha^nh+rb*(KHAmax-kha)-cha
f(9)=(1-phiB)*clb^(-sigmaB)*lambB*(wb*hlb*nlb)^(-phiB)*wb*nlb-kappaB*hlb^(1/vB)
f(10)=(1-phiB)*chb^(-sigmaB)*lambB*(wb*hhb*nhb)^(-phiB)*wb*nhb-kappaB*hhb^(1/vB)
f(11)=nlb*ra*klb^(nlb-1)-rb
f(12)=nhb*ra*khb^(nhb-1)-rb
f(13)=lambB*(wb*hlb*nlb)^(1-phiB)+rb*klb^nlb+ra*(KLBmax-klb)-clb
f(14)=lambB*(wb*hhb*nhb)^(1-phiB)+rb*khb^nlb+ra*(KHBmax-khb)-chb
f(15)=(1-thetaB)*zeta*(klb+khb-KAd+kla+kha)^(-thetaB)*(nlb*hlb+nhb*hhb)^(thetaB)-rb
f(16)=thetaB*zeta*(klb+khb-KAd+kla+kha)^(1-thetaB)*(nlb*hlb+nhb*hhb)^(thetaB-1)-wb